language: minimal

git:
  depth: 20

stages:
#  - lint
#  - build
#  - installer
  - test

env:
  global:
    - PYENV_ROOT="$HOME/pyenv.root"
    - CONFIG=release
    - VERA=false
    - PROJECT=studio
    - TESTS=true
    - TRANSLATIONS=false
    - INSTALLER=false
    - BUILD_TIMEOUT=2400
    - EARLY_START_DOCKER_PULL_PID=$( if [ $TRAVIS_OS_NAME = 'linux' ] ; then time docker pull trikset/linux-builder ; else true ; fi >&2 & echo $!)
    - HEARTBEAT=$(while sleep 100; do echo "=====[ $SECONDS seconds, still building... ]====="; done >&2 & echo $! )
    - ALL_TESTS="./robots_kitBase_unittests && ./robots_interpreterCore_unittests && ./robots_twoDModel_unittests && ./trik-v62-qts-generator-tests && ./robots_utils_unittests && ./run-simulator-tests.sh"
    - QMAKE_EXTRA="CONFIG+=tests CONFIG+=noPch CONFIG+=ccache"
    - TRIK_QT="$HOME/TRIK_Qt"
    - secure: "Djp1JuoB/dDxIQwmYfaJIflulGaZk69djacFE4L/ippcFfcN9As/dzTvBHjHNV2urZoNGAH5iuIGgX0b6aMKIzQRcGbLOrr7yx3SiT/hJ/sh6tnDoiz6kVDiq6Nubf+Mpvgjbm3wuseqcdK4LzHLVv4bZh7cB+JPG4x5PndbD2RyaCoSwdqsZ+fZj0ixteVsGrexSW/w4ZPiAtTfxsRKYJmivLl3jQNm6b0g3AEr37BO/M88xSaECa3WagR6bSgWlNqhftBq51Qk/242LIhLKlLEDLNr4zj04SctO+dZQqT8T99REihHfgbzYg+oFG2/M4fpkxsHykKG8t+Ssgx6iuIMwP8nI/wH6zY68xsmLaMR0rXT8gRxXz2w6z1xwQlXbcRYTWH/PKrLFwIN4d+//GzHHnsh/e6TM6T5pv8t704wmcCer1MbHbHqfRUjK3CAKE62HzsHh4En1PmFsW5kCedmDwTvMvTMiwR7Sru0TrUJ4ldXXbIcfGwisJfhntUQ53eWsN0uZ0FjfZqLQtGEDpn4m+WZwf3cMXKicX18mGXeRsnEOOxK/b62qBTh+hBK+3li69jflVqJJzWqVa4GDkL10OgW5hk/IHCDiTPLqeg/6eCefZFn7FcT4iRdG5CzROfXY5Ep0Gf/ia+uBZBpvlQMQ84/WBLMhgHXGCJGwqU="
    - secure: "Bs6NDzxktMXnE4I8kctP7UZUx+/qaIyxVemruzhRMBrUT3yk68tvyKVmWy3z1/e1tR3Wm1GlJKk+NgdWporksgMJiHKYhkxtwM0GWkfR6lgQyUiZCYubinr4PU9/DsXtPa21lq/bEqXLe3Lz7BDOpWZ5lY8j58tCwZB+OsbmYiGdSsxXr1AtSKsX9t985J+iOG1lzFJT1BWXBnHxIyk24bGo7j1kg4IDD0OE5uxf1Q6COIOOWhOBAx6xCUgpnT/Myv4GPFv0kenlmyXLqB9t3Dndxd+Y4D0v/ak35TjqhCip6uTwJVjMDWX62Twrb2E/YK53nnn2nsSYlcgxKy5CQyKz3x8YmhqkOeXMx9OH4gT5pD1JRSk+4nJ+ht9Y9UCJX0vyDJKiHtWLzKLXP8B8xaABTlmqYAfiqkaEHO3fUst+9AA+0SkuBWsGOIFfQ2R6kVsvUii9Tm73dAc9z1q35zFkYQLoZ9mnXa7al+RxLQPhDeKuPdCa4DyQZS1cDbRJmMCqtoZGbwr/LEWpp0KYsZPlaMRSM1WvUwngG98M7ojZEyF1u6BVYbjnbCQKAM3qVFpGKbSMOoVPRPTU+DeSD5lFWDYn5Rc3Ls4vp/giAPfB7Vxpej6NrNLulMb/DPfC5Z9XdJBg9ZqAuYMogyZo8dgX0OAPOuDTwNZEv156x8g="



cache:
  timeout: 1000
  directories:
    - $PYENV_ROOT
    - $HOME/.ccache
    - $TRIK_QT

addons:
  artifacts:
    paths:
      - build.log

branches:
  except:
    - /dependabot.*/

matrix:
  include:
    - stage: test
      os: linux
      env: CLEAN_ENV_TEST=true
      script:
      - ./buildScripts/travis/run_clean_env_test.sh
